export const DICT = {
  fr: {
    nPrev: "Aperçu", nDet: "Détections", nInt: "Intégrité", nSpec: "Spectrogrammes", nTags: "Tags", nConv: "Conversion", nExp: "Export", nPipe: "Pipeline", nDl: "Télécharger", nDoc: "Docs",
    kick: "Open source · Rust + Tauri · macOS · Windows · Linux",
    h1a: "Votre lossless est-il", h1b: "vraiment lossless ?",
    sub: "FlacCompagnon examine vos fichiers audio : authenticité, loudness, stéréo, dynamique et intégrité. Dans une application native ou depuis le terminal, retrouvez les mesures utiles pour comprendre votre bibliothèque.",
    ctaDl: "Télécharger", ctaGh: "Voir sur GitHub",
    note: "Gratuit · Application MIT · Core MPL-2.0 · L’analyse ne modifie jamais vos fichiers",
    s1k: "Aperçu", s1t: "L'analyse en un coup d'œil",
    s1p: "Déposez un dossier ou des fichiers : chaque piste est décodée et passée au crible en parallèle. Un tag coloré par détection — et au survol, l'explication du verdict.",
    cap1: "Aperçu illustratif de l’interface — survolez les détections pour lire leur interprétation.",
    thFile: "Fichier", thFmt: "Format", thDur: "Durée", thSr: "Échantillonnage", thBits: "Bits réels", thCut: "Cut-off", thDet: "Détections",
    sumCount: "4 fichiers", chClean: "2 clean", chUps: "1 upsamplé", chTr: "1 transcodé",
    tipClean: "Aucune détection : contenu plein jusqu'à ~21,9 kHz, pas de signature lossy.",
    tipDark: "Un master acoustique naturellement sombre : le spectre s'arrête à 18,6 kHz parce que personne n'a joué au-dessus, pas parce qu'un codec l'a coupé. Aucune grille de quantification n'a été trouvée — le fichier est déclaré propre.",
    s2k: "Détections", s2t: "Trois détections indépendantes",
    s2p: "Trois recherches indépendantes examinent la précision des échantillons, la bande de fréquences et les traces de codecs avec perte. Leurs méthodes et leurs limites sont expliquées dans la documentation.",
    s2note: "Une détection est un indice, pas un certificat d’origine. Des traitements ou des choix artistiques peuvent imiter ou masquer une signature. Clean signifie qu’aucun détecteur n’a levé d’alerte. Croisez les mesures, le spectrogramme et l’écoute.",
    d1t: "Upscaling — fausse résolution",
    d1p: "La mesure cherche les bits toujours inutilisés, puis une grille de précision inférieure sous de faibles résidus. Elle distingue une profondeur exacte d’une estimation, affichée avec ≈.",
    d1tip: "Marqué Upscaled : profondeur déclarée 24 bits, profondeur effective ≤ 16 bits. Les 8 bits de poids faible ne portent aucune information réelle.",
    d1cap: "24 bits déclarés — les 8 bits bas sont vides",
    d2t: "Upsampling — faux échantillonnage",
    d2p: "Dans un fichier à plus de 48 kHz, l’analyse recherche une bande haute durablement vide. Cette forme est compatible avec une source de fréquence inférieure, mais aussi avec un master naturellement limité ou filtré.",
    d2tip: "Exemple de bande haute vide dans un conteneur 96 kHz. Le détecteur utilise des fenêtres MDCT ; le cutoff affiché est une mesure FFT distincte. La provenance n’est pas prouvée.",
    d2cap: "Le mur du cut-off à 22,05 kHz",
    d3t: "Transcoding — source lossy",
    d3p: "L’analyse recherche les grilles de quantification que peuvent laisser l’AAC et le MP3 dans l’audio décodé. Leur présence est évaluée statistiquement, avec une calibration encore préliminaire.",
    d3tip: "Exemple de signature de codec détectée. Un score de grille n’est pas une probabilité que le fichier soit lossy ; la source, les traitements et les limites du test doivent être pris en compte.",
    d3cap: "Les coefficients « snappent » sur la grille AAC",
    s3k: "Toutes les analyses", s3t: "Chaque mesure répond à une question.",
    s3p: "Explorez les analyses par famille. Chaque lien mène à une explication simple, puis à la méthode détaillée, aux limites et aux exemples de test.",
    s4k: "Spectrogrammes", s4t: "Voir ce que les chiffres suggèrent",
    s4p: "Un clic génère un spectrogramme haute résolution par piste, avec axe de fréquences gradué jusqu'à la fréquence de Nyquist (la moitié de l'échantillonnage, soit 22,05 kHz pour un CD à 44,1 kHz). Le cut-off se voit à l'œil nu.",
    s4n1: "Rendu via ffmpeg, détecté automatiquement sur votre système.",
    s4n2: "Un dossier <code>spectrograms/</code> est créé dans chaque dossier contenant des fichiers audio, et un PNG est généré par piste — uniquement si vous cliquez sur le bouton « Generate spectrograms ».",
    s4n3: "Plus rapide encore : <strong>écoutez</strong>. Un clic sur la vignette d'une ligne lance la lecture, avec une barre de transport en pied de liste. Ce n'est pas un lecteur audio à proprement parler — juste de quoi confronter un verdict à votre oreille sans quitter l'application.",
    s5k: "Pipeline", s5t: "Comment ça marche",
    s5p: "Glissez-déposez un dossier ou des fichiers — ou choisissez-les avec le bouton d'import. Chaque piste est décodée, puis passée en revue par une batterie d'analyses, et le verdict s'affiche.",
    p1: "dossier déposé", p2: "décodage · symphonia", p3: "analyse streaming",
    p3a: "FFT ▸ cut-off", p3b: "AAC / MP3 ▸ grilles", p3c: "bits effectifs", p3d: "LUFS · phase · niveaux",
    p4: "table de résultats",
    s5note: "Le moteur Rust est partagé par l’application, la CLI et Aède. Les mesures en continu et la vérification MD5 FLAC partagent le décodage ; la recherche des signatures de codecs peut demander un travail supplémentaire.",
    s6k: "Téléchargement", s6t: "Une petite app native",
    s6p: "Installateurs construits par GitHub Actions pour les trois plateformes. Les archives de la CLI sont proposées séparément dans les releases qui les incluent.",
    dlBtn: "Télécharger",
    ffnote: "ffmpeg n'est requis que pour les spectrogrammes et pour l'analyse de contenu des fichiers DSD — le reste de l'analyse s'en passe entièrement.",
    ffinstall: "Pas de ffmpeg installé ? Consultez le <a href=\"https://github.com/craft-and-code/FlacCompagnon#prerequisites\" target=\"_blank\" rel=\"noopener\">README sur GitHub</a> pour l'installer sur macOS, Windows ou Linux.",
    s8k: "Tags", s8t: "Corriger, pas seulement constater",
    s8p: "Sélectionnez une ou plusieurs pistes — un volet d'édition s'ouvre à gauche, avec les champs habituels : titre, artiste, album, artiste d'album, compositeur, année, genre, n° de piste et de disque, commentaire, compilation. C'est le <strong>seul endroit de l'application qui écrit dans vos fichiers</strong>, et uniquement quand vous cliquez sur <strong>Save</strong>.",
    t1t: "Édition par lot",
    t1p: "Sélectionnez tout un album : chaque champ affiche la valeur commune ou un badge « plusieurs valeurs ». Seuls les champs que vous modifiez sont écrits — corriger l'album de 12 pistes n'écrase jamais leurs titres respectifs. Un bouton dédié renumérote la sélection de 1 à N d’un coup, dans l’ordre du tableau.",
    t2t: "Pochettes",
    t2p: "Choisissez le rôle de l’image : face avant, dos, livret… La sélection affiche l’image correspondante, et les imports ou exports suivent ce rôle. La proportion originale est conservée ; cliquez pour voir l’image en grand.",
    t3t: "Recherche en ligne",
    t3p: "Le bouton <strong>Search online</strong> interroge <strong>MusicBrainz</strong> et, si vous fournissez votre jeton personnel, <strong>Discogs</strong>. Si le fichier porte déjà un identifiant MusicBrainz (tagué par Picard), la bonne release est trouvée directement, sans recherche approximative.",
    s8note: "Les résultats en ligne <strong>pré-remplissent</strong> le volet : rien n'est écrit tant que vous n'avez pas relu et cliqué sur Save — et <strong>Reset</strong> annule tout. C'est la seule fonction qui utilise le réseau, et jamais sans un clic de votre part.",
    s9k: "Conversion", s9t: "Convertir sans casser le rangement",
    s9p: "Un volet dédié, symétrique de celui des tags : déposez-y des pistes ou des dossiers, choisissez un format, et l'arborescence d'origine est <strong>reproduite à l'identique</strong> sous le dossier de destination. Les fichiers importés pour la conversion ne rejoignent jamais le tableau d'analyse — les deux listes sont indépendantes.",
    cf1: "sans perte", cf2: "libre de droits", cf3: "compatible partout", cf4: "PCM 16 bits",
    s9n1: "Opus et MP3 proposent un débit ; FLAC et WAV n'en ont pas à choisir. Le WAV produit est fixé en 16 bits, quelle que soit la profondeur de la source.",
    s9n2: "Une case à cocher copie aussi tout ce qui n'est pas de l'audio — pochettes, playlists, spectrogrammes déjà générés — à la même place dans l'arborescence copiée.",
    s9note: "Vos fichiers d'origine ne sont ni déplacés ni modifiés : la conversion écrit ailleurs, toujours. La lecture en cours se met en pause pendant le traitement (les encodeurs occupent tous les cœurs) et reprend ensuite toute seule. <strong>Cancel</strong> arrête le lot et efface les fichiers déjà écrits par celui-ci — sans toucher à ce que le dossier contenait avant.",
    s7k: "Export", s7t: "Emportez vos résultats",
    s7p: "Un clic sur <strong>Save…</strong> écrit deux fichiers, même nom, même dossier : un <code>.csv</code> — une ligne par piste, toutes les colonnes de l'analyse, prêt pour un tableur — et un <code>.json</code> qui conserve l'analyse complète, y compris le détail de chaque détection. Le nom et l'emplacement proposés reprennent le dossier analysé.",
    s7n2: "Déposez un <code>.json</code> déjà exporté sur la liste pour recharger le tableau tel quel — aucun fichier audio n'est redécodé. Pas de bouton dédié : c'est le même geste que déposer un dossier.",
    s7m3u: "<strong>Export playlist…</strong> écrit une playlist <strong>M3U</strong> dans l'ordre affiché à l'écran — y compris après avoir réorganisé les lignes à la souris. Au choix : M3U étendu (<code>.m3u8</code>, avec les durées et « Artiste — Titre ») par défaut, ou M3U simple (<code>.m3u</code>, les chemins seuls).",
    s7n1: "Astuce : la corbeille en bout de ligne écarte un fichier de la liste — il ne figurera dans aucun des deux fichiers exportés.",
    refT: "Références",
    ref1: "J. Lacroix, Y. Prime, A. Remy & O. Derrien — « Lossless Audio Checker: A Software for the Detection of Upscaling, Upsampling, and Transcoding in Lossless Musical Tracks », AES 139th Convention, Paper 9416, New York, 2015.",
    ref2: "O. Derrien et al. — « Detection of Genuine Lossless Audio Files: Application to the MPEG-AAC Codec », Journal of the AES, 2019.",
    ref3: "FlacCompagnon est un projet indépendant. Les mesures et leurs limites sont documentées ; aucune détection ne constitue à elle seule une preuve de provenance.",
    ftLeft: "© 2026 FlacCompagnon · Application MIT · Core MPL-2.0 · Construit en Rust + Tauri",
  },
  en: {
    nPrev: "Preview", nDet: "Detections", nInt: "Integrity", nSpec: "Spectrograms", nTags: "Tags", nConv: "Conversion", nExp: "Export", nPipe: "Pipeline", nDl: "Download", nDoc: "Docs",
    kick: "Open source · Rust + Tauri · macOS · Windows · Linux",
    h1a: "Is your lossless", h1b: "actually lossless?",
    sub: "FlacCompagnon examines your audio: authenticity, loudness, stereo, dynamics and integrity. In a native app or from the terminal, find the measurements that help you understand your library.",
    ctaDl: "Download", ctaGh: "View on GitHub",
    note: "Free · App MIT · Core MPL-2.0 · Analysis never modifies your files",
    s1k: "Preview", s1t: "The analysis at a glance",
    s1p: "Drop a folder or files: every track is decoded and screened in parallel. One coloured tag per detection — hover it for the reasoning behind the verdict.",
    cap1: "Illustrative interface preview — hover over detections to read their interpretation.",
    thFile: "File", thFmt: "Format", thDur: "Length", thSr: "Sample rate", thBits: "Real bits", thCut: "Cut-off", thDet: "Detections",
    sumCount: "4 files", chClean: "2 clean", chUps: "1 upsampled", chTr: "1 transcoded",
    tipClean: "No detection: full-band content up to ~21.9 kHz, no lossy signature.",
    tipDark: "A naturally dark acoustic master: the spectrum stops at 18.6 kHz because nobody played above it, not because a codec cut it off. No quantization lattice was found — the file is reported clean.",
    s2k: "Detections", s2t: "Three independent detections",
    s2p: "Three independent checks examine sample precision, frequency bandwidth and traces of lossy codecs. Their methods and limits are explained in the documentation.",
    s2note: "A detection is a clue, not a certificate of origin. Processing and artistic choices can imitate or hide a signature. Clean means no detector raised a finding. Combine measurements, spectrograms and listening.",
    d1t: "Upscaling — fake resolution",
    d1p: "The meter looks for consistently unused bits, then for a lower-depth grid beneath small residuals. Exact depth is distinguished from an estimate, marked with ≈.",
    d1tip: "Flagged Upscaled: declared depth 24-bit, effective depth ≤ 16-bit. The 8 low bits carry no real information.",
    d1cap: "Declared 24-bit — the 8 low bits are empty",
    d2t: "Upsampling — fake sample rate",
    d2p: "In files above 48 kHz, the analysis searches for a persistently empty high band. This is consistent with a lower-rate source, but also with a naturally limited or filtered master.",
    d2tip: "Example of an empty high band in a 96 kHz container. The detector uses MDCT windows; the displayed cutoff is a separate FFT measurement. Provenance is not established.",
    d2cap: "The cut-off wall at 22.05 kHz",
    d3t: "Transcoding — lossy source",
    d3p: "The analysis searches for quantization grids that AAC and MP3 can leave in decoded audio. Their presence is evaluated statistically, with calibration still preliminary.",
    d3tip: "Example of a detected codec signature. A lattice score is not a probability that the file is lossy; source material, processing and test limits must be considered.",
    d3cap: "Coefficients snapping onto the AAC grid",
    s3k: "All analyses", s3t: "Every measurement answers a question.",
    s3p: "Explore the analyses by family. Each link opens a plain-language explanation, followed by the detailed method, limits and test examples.",
    s4k: "Spectrograms", s4t: "See what the numbers suggest",
    s4p: "One click renders a high-resolution spectrogram per track, with a labelled frequency axis up to the Nyquist frequency (half the sample rate, e.g. 22.05 kHz for a 44.1 kHz CD). The cut-off is visible to the naked eye.",
    s4n1: "Rendered via ffmpeg, located automatically on your system.",
    s4n2: "A <code>spectrograms/</code> folder is created inside each folder that holds audio files, and one PNG per track is generated — only when you click the “Generate spectrograms” button.",
    s4n3: "Quicker still: <strong>listen</strong>. Clicking a row's thumbnail starts playback, with a transport bar under the list. This is not really an audio player — just enough to hold a verdict up against your own ears without leaving the app.",
    s5k: "Pipeline", s5t: "How it works",
    s5p: "Drag and drop a folder or files — or pick them with the import button. Each track is decoded, then run through a battery of analyses, and the verdict appears.",
    p1: "dropped folder", p2: "decode · symphonia", p3: "streaming analyzer",
    p3a: "FFT ▸ cut-off", p3b: "AAC / MP3 ▸ grids", p3c: "effective bits", p3d: "LUFS · phase · levels",
    p4: "results table",
    s5note: "The Rust engine is shared by the app, CLI and Aède. Streaming measurements and FLAC MD5 verification share decoding; searching for codec signatures can require additional work.",
    s6k: "Download", s6t: "A small native app",
    s6p: "Installers built by GitHub Actions for all three platforms. Separate CLI archives are available in releases that include them.",
    dlBtn: "Download",
    ffnote: "ffmpeg is only needed for spectrograms and for DSD content analysis — the rest of the analysis works entirely without it.",
    ffinstall: "No ffmpeg installed? See the <a href=\"https://github.com/craft-and-code/FlacCompagnon#prerequisites\" target=\"_blank\" rel=\"noopener\">README on GitHub</a> to install it on macOS, Windows or Linux.",
    s8k: "Tags", s8t: "Fix it, don't just flag it",
    s8p: "Select one or more tracks and an editing panel opens on the left, with the usual fields: title, artist, album, album artist, composer, year, genre, track and disc numbers, comment, compilation. It is the <strong>only place in the app that writes to your files</strong>, and only when you click <strong>Save</strong>.",
    t1t: "Batch editing",
    t1p: "Select a whole album: each field shows either the shared value or a “multiple values” badge. Only the fields you actually touch are written — fixing the album on 12 tracks never flattens their individual titles. A dedicated button renumbers the selection 1 through N in one go, in table order.",
    t2t: "Cover art",
    t2p: "Choose the image role: front cover, back cover, booklet… The selection displays the corresponding picture, and imports or exports follow that role. Original proportions are preserved; click to view it full size.",
    t3t: "Online lookup",
    t3p: "The <strong>Search online</strong> button queries <strong>MusicBrainz</strong> and, if you supply your own personal token, <strong>Discogs</strong>. When the file already carries a MusicBrainz ID (tagged with Picard), the right release is found directly — no fuzzy searching.",
    s8note: "Online results <strong>pre-fill</strong> the panel: nothing is written until you have reviewed it and pressed Save — and <strong>Reset</strong> discards everything. This is the only feature that uses the network, and never without a click from you.",
    s9k: "Conversion", s9t: "Convert without wrecking your filing",
    s9p: "A dedicated panel, mirroring the tag one: drop tracks or folders into it, pick a format, and the source folder structure is <strong>reproduced exactly</strong> under the destination you choose. Files imported for conversion never join the analysis table — the two lists are independent.",
    cf1: "lossless", cf2: "royalty-free", cf3: "plays everywhere", cf4: "16-bit PCM",
    s9n1: "Opus and MP3 offer a bitrate; FLAC and WAV have none to choose. The WAV written is fixed at 16-bit, whatever the source depth.",
    s9n2: "A checkbox also copies everything that is not audio — covers, playlists, spectrograms you already generated — to the same place in the copied tree.",
    s9note: "Your originals are neither moved nor modified: conversion always writes somewhere else. Playback pauses for the duration (the encoders take every core) and resumes on its own afterwards. <strong>Cancel</strong> stops the batch and deletes the files it had already written — leaving whatever the folder held beforehand untouched.",
    s7k: "Export", s7t: "Take your results with you",
    s7p: "Clicking <strong>Save…</strong> writes two files, same name, same folder: a <code>.csv</code> — one row per track, every analysis column, ready for a spreadsheet — and a <code>.json</code> that keeps the full analysis, including each detection's detail. The suggested name and location follow the analyzed folder.",
    s7n2: "Drop a previously-exported <code>.json</code> onto the list to reload the table as-is — no audio is re-decoded. No dedicated button: same gesture as dropping a folder.",
    s7m3u: "<strong>Export playlist…</strong> writes an <strong>M3U</strong> playlist in the order shown on screen — including any manual reordering you did by dragging rows. Your choice of Extended M3U (<code>.m3u8</code>, with durations and “Artist — Title”) by default, or Simple M3U (<code>.m3u</code>, paths only).",
    s7n1: "Tip: the trash icon at the end of a row removes a file from the list — it will not appear in either exported file.",
    refT: "References",
    ref1: "J. Lacroix, Y. Prime, A. Remy & O. Derrien — “Lossless Audio Checker: A Software for the Detection of Upscaling, Upsampling, and Transcoding in Lossless Musical Tracks”, AES 139th Convention, Paper 9416, New York, 2015.",
    ref2: "O. Derrien et al. — “Detection of Genuine Lossless Audio Files: Application to the MPEG-AAC Codec”, Journal of the AES, 2019.",
    ref3: "FlacCompagnon is an independent project. Measurements and their limits are documented; no detection alone constitutes proof of provenance.",
    ftLeft: "© 2026 FlacCompagnon · App MIT · Core MPL-2.0 · Built with Rust + Tauri",
  },
};
