[package]
name = "flaccompagnon-cli"
description = "Command-line audio analysis with FlacCompagnon."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "flaccompagnon"
path = "src/main.rs"

[dependencies]
indicatif = "0.18"
flaccompagnon-core = { path = "../core" }

[dev-dependencies]
indicatif = { version = "0.18", features = ["in_memory"] }
tempfile = "3"
hound = "3"
